// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtakuDex.Models;

#nullable disable

namespace OtakuDex.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617123510_AddAnimeDatabase")]
    partial class AddAnimeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OtakuDex.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Episodes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Studio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("OtakuDex.Models.AnimeDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Episodes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MalScore")
                        .HasColumnType("float");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AnimeDatabase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/5/73199l.jpg",
                            Episodes = 24,
                            Genre = "Sci-Fi,Thriller,Drama",
                            MalScore = 9.0999999999999996,
                            Studio = "White Fox",
                            Synopsis = "A self-proclaimed mad scientist discovers time travel and must face its consequences.",
                            Title = "Steins;Gate",
                            Year = 2011
                        },
                        new
                        {
                            Id = 2,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1337/99013l.jpg",
                            Episodes = 148,
                            Genre = "Action,Adventure,Fantasy",
                            MalScore = 9.0,
                            Studio = "Madhouse",
                            Synopsis = "A young boy searches for his missing father in a world of hunters.",
                            Title = "Hunter x Hunter (2011)",
                            Year = 2011
                        },
                        new
                        {
                            Id = 3,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1314/108888l.jpg",
                            Episodes = 26,
                            Genre = "Action,Sci-Fi,Drama,Psychological",
                            MalScore = 8.5,
                            Studio = "Gainax",
                            Synopsis = "Teenagers pilot giant mechs to protect humanity from mysterious beings.",
                            Title = "Neon Genesis Evangelion",
                            Year = 1995
                        },
                        new
                        {
                            Id = 4,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/4/19644l.jpg",
                            Episodes = 26,
                            Genre = "Action,Sci-Fi,Drama",
                            MalScore = 8.8000000000000007,
                            Studio = "Sunrise",
                            Synopsis = "A ragtag crew of bounty hunters travel the solar system.",
                            Title = "Cowboy Bebop",
                            Year = 1998
                        },
                        new
                        {
                            Id = 5,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/6/73245l.jpg",
                            Episodes = 1000,
                            Genre = "Action,Adventure,Comedy,Fantasy",
                            MalScore = 8.6999999999999993,
                            Studio = "Toei Animation",
                            Synopsis = "A young pirate sets out to find the ultimate treasure and become King of the Pirates.",
                            Title = "One Piece",
                            Year = 1999
                        },
                        new
                        {
                            Id = 6,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1565/111305l.jpg",
                            Episodes = 500,
                            Genre = "Action,Adventure,Fantasy",
                            MalScore = 8.1999999999999993,
                            Studio = "Pierrot",
                            Synopsis = "Naruto continues his journey to become Hokage and save his friend Sasuke.",
                            Title = "Naruto Shippuden",
                            Year = 2007
                        },
                        new
                        {
                            Id = 7,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/9/9453l.jpg",
                            Episodes = 37,
                            Genre = "Thriller,Supernatural,Drama,Psychological",
                            MalScore = 8.5999999999999996,
                            Studio = "Madhouse",
                            Synopsis = "A genius student finds a notebook that can kill anyone whose name is written in it.",
                            Title = "Death Note",
                            Year = 2006
                        },
                        new
                        {
                            Id = 8,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/5/50331l.jpg",
                            Episodes = 25,
                            Genre = "Action,Sci-Fi,Drama,Mecha",
                            MalScore = 8.6999999999999993,
                            Studio = "Sunrise",
                            Synopsis = "An exiled prince gains the power to command anyone and leads a rebellion.",
                            Title = "Code Geass",
                            Year = 2006
                        },
                        new
                        {
                            Id = 9,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/6/86733l.jpg",
                            Episodes = 13,
                            Genre = "Adventure,Drama,Fantasy,Sci-Fi",
                            MalScore = 8.6999999999999993,
                            Studio = "Kinema Citrus",
                            Synopsis = "A girl and a robot boy descend into a mysterious and dangerous abyss.",
                            Title = "Made in Abyss",
                            Year = 2017
                        },
                        new
                        {
                            Id = 10,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1522/128039l.jpg",
                            Episodes = 25,
                            Genre = "Drama,Fantasy,Psychological,Thriller",
                            MalScore = 8.3000000000000007,
                            Studio = "White Fox",
                            Synopsis = "A boy is transported to a fantasy world and discovers he revives upon death.",
                            Title = "Re:Zero",
                            Year = 2016
                        },
                        new
                        {
                            Id = 11,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/11/39717l.jpg",
                            Episodes = 25,
                            Genre = "Action,Adventure,Fantasy,Romance",
                            MalScore = 7.2000000000000002,
                            Studio = "A-1 Pictures",
                            Synopsis = "Players are trapped in a virtual reality MMORPG and must clear it to escape.",
                            Title = "Sword Art Online",
                            Year = 2012
                        },
                        new
                        {
                            Id = 12,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1074/111944l.jpg",
                            Episodes = 12,
                            Genre = "Comedy,Fantasy,Ecchi",
                            MalScore = 8.0999999999999996,
                            Studio = "Madhouse",
                            Synopsis = "Genius gamer siblings are transported to a world where everything is decided by games.",
                            Title = "No Game No Life",
                            Year = 2014
                        },
                        new
                        {
                            Id = 13,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/7/88211l.jpg",
                            Episodes = 13,
                            Genre = "Action,Adventure,Fantasy",
                            MalScore = 7.9000000000000004,
                            Studio = "Madhouse",
                            Synopsis = "A player is stuck in an RPG as his character and builds his own empire.",
                            Title = "Overlord",
                            Year = 2015
                        },
                        new
                        {
                            Id = 14,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1506/117736l.jpg",
                            Episodes = 24,
                            Genre = "Action,Adventure,Comedy,Fantasy",
                            MalScore = 8.0999999999999996,
                            Studio = "8bit",
                            Synopsis = "A man reincarnates as a slime in a fantasy world and builds his own nation.",
                            Title = "That Time I Got Reincarnated as a Slime",
                            Year = 2018
                        },
                        new
                        {
                            Id = 15,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/2/88336l.jpg",
                            Episodes = 170,
                            Genre = "Action,Comedy,Fantasy",
                            MalScore = 8.0999999999999996,
                            Studio = "Pierrot",
                            Synopsis = "A boy born without magic powers dreams of becoming the Wizard King.",
                            Title = "Black Clover",
                            Year = 2017
                        },
                        new
                        {
                            Id = 16,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/3/40451l.jpg",
                            Episodes = 366,
                            Genre = "Action,Supernatural,Adventure",
                            MalScore = 7.9000000000000004,
                            Studio = "Pierrot",
                            Synopsis = "A teenager gains the powers of a Soul Reaper and protects the living from evil spirits.",
                            Title = "Bleach",
                            Year = 2004
                        },
                        new
                        {
                            Id = 17,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/5/18179l.jpg",
                            Episodes = 175,
                            Genre = "Action,Adventure,Comedy,Fantasy",
                            MalScore = 7.9000000000000004,
                            Studio = "A-1 Pictures",
                            Synopsis = "A wizard guild takes on dangerous missions in a magical world.",
                            Title = "Fairy Tail",
                            Year = 2009
                        },
                        new
                        {
                            Id = 18,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/13/22128l.jpg",
                            Episodes = 25,
                            Genre = "Comedy,Drama,Romance,School",
                            MalScore = 8.1999999999999993,
                            Studio = "J.C.Staff",
                            Synopsis = "Two mismatched teens team up to help each other confess their crushes.",
                            Title = "Toradora",
                            Year = 2008
                        },
                        new
                        {
                            Id = 19,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1299/110774l.jpg",
                            Episodes = 24,
                            Genre = "Drama,Romance,Slice of Life",
                            MalScore = 9.0,
                            Studio = "Kyoto Animation",
                            Synopsis = "A delinquent and a girl form bonds that change their lives forever.",
                            Title = "Clannad: After Story",
                            Year = 2008
                        },
                        new
                        {
                            Id = 20,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1887/117644l.jpg",
                            Episodes = 11,
                            Genre = "Drama,Romance,Supernatural",
                            MalScore = 8.5999999999999996,
                            Studio = "A-1 Pictures",
                            Synopsis = "A group of childhood friends reunite after the ghost of their dead friend appears.",
                            Title = "Anohana",
                            Year = 2011
                        },
                        new
                        {
                            Id = 21,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1221/96022l.jpg",
                            Episodes = 24,
                            Genre = "Action,Adventure,Fantasy,Romance",
                            MalScore = 7.7999999999999998,
                            Studio = "A-1 Pictures",
                            Synopsis = "Kirito wakes up in an Underworld and must uncover the truth.",
                            Title = "Sword Art Online: Alicization",
                            Year = 2018
                        },
                        new
                        {
                            Id = 22,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1935/99703l.jpg",
                            Episodes = 12,
                            Genre = "Horror,Mystery,Sci-Fi,Thriller",
                            MalScore = 8.5999999999999996,
                            Studio = "CloverWorks",
                            Synopsis = "Orphaned children discover their idyllic home hides a dark secret.",
                            Title = "The Promised Neverland",
                            Year = 2019
                        },
                        new
                        {
                            Id = 23,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",
                            Episodes = 12,
                            Genre = "Action,Comedy,Supernatural",
                            MalScore = 8.5999999999999996,
                            Studio = "Bones",
                            Synopsis = "An overpowered psychic boy navigates life while trying to remain emotionally stable.",
                            Title = "Mob Psycho 100",
                            Year = 2016
                        },
                        new
                        {
                            Id = 24,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1255/82685l.jpg",
                            Episodes = 13,
                            Genre = "Comedy,Drama,Romance,School",
                            MalScore = 8.0,
                            Studio = "Brain's Base",
                            Synopsis = "A cynical loner joins a club for helping others and questions social norms.",
                            Title = "Oregairu",
                            Year = 2013
                        },
                        new
                        {
                            Id = 25,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1500/103005l.jpg",
                            Episodes = 1,
                            Genre = "Action,Adventure,Fantasy,Romance",
                            MalScore = 7.9000000000000004,
                            Studio = "A-1 Pictures",
                            Synopsis = "A retelling of SAO from Asuna's perspective, floor by floor.",
                            Title = "Sword Art Online: Progressive",
                            Year = 2021
                        },
                        new
                        {
                            Id = 26,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1441/99991l.jpg",
                            Episodes = 12,
                            Genre = "Drama,School,Slice of Life",
                            MalScore = 8.0999999999999996,
                            Studio = "Seven Arcs",
                            Synopsis = "A delinquent discovers his passion for art and strives to enter Tokyo University of the Arts.",
                            Title = "Blue Period",
                            Year = 2021
                        },
                        new
                        {
                            Id = 27,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/3/67177l.jpg",
                            Episodes = 26,
                            Genre = "Adventure,Fantasy,Mystery,Slice of Life,Supernatural",
                            MalScore = 8.6999999999999993,
                            Studio = "Artland",
                            Synopsis = "A traveler investigates mysterious lifeforms called Mushi that affect people's lives.",
                            Title = "Mushishi",
                            Year = 2005
                        },
                        new
                        {
                            Id = 28,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1521/99674l.jpg",
                            Episodes = 26,
                            Genre = "Action,Adventure,Comedy,Historical",
                            MalScore = 8.5,
                            Studio = "Manglobe",
                            Synopsis = "Two skilled samurai and a girl search for a specific samurai who smells of sunflowers.",
                            Title = "Samurai Champloo",
                            Year = 2004
                        },
                        new
                        {
                            Id = 29,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/3/73474l.jpg",
                            Episodes = 24,
                            Genre = "Action,Horror,Psychological,Sci-Fi",
                            MalScore = 8.4000000000000004,
                            Studio = "Madhouse",
                            Synopsis = "A teen's hand is taken over by an alien parasite and they must coexist.",
                            Title = "Parasyte",
                            Year = 2014
                        },
                        new
                        {
                            Id = 30,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/5/64449l.jpg",
                            Episodes = 12,
                            Genre = "Action,Horror,Mystery,Supernatural",
                            MalScore = 7.7999999999999998,
                            Studio = "Pierrot",
                            Synopsis = "A college student becomes half-ghoul after a chance encounter and must survive in both worlds.",
                            Title = "Tokyo Ghoul",
                            Year = 2014
                        },
                        new
                        {
                            Id = 31,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
                            Episodes = 24,
                            Genre = "Action,Adventure,Fantasy,Romance",
                            MalScore = 7.2999999999999998,
                            Studio = "A-1 Pictures",
                            Synopsis = "Kirito enters a new VR game to investigate a mysterious death.",
                            Title = "Sword Art Online II",
                            Year = 2014
                        },
                        new
                        {
                            Id = 32,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1988/119581l.jpg",
                            Episodes = 1,
                            Genre = "Drama,Romance,School",
                            MalScore = 8.9000000000000004,
                            Studio = "Kyoto Animation",
                            Synopsis = "A former bully seeks redemption by reconnecting with a deaf girl he once tormented.",
                            Title = "A Silent Voice",
                            Year = 2016
                        },
                        new
                        {
                            Id = 33,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
                            Episodes = 1,
                            Genre = "Drama,Romance,Supernatural",
                            MalScore = 8.9000000000000004,
                            Studio = "CoMix Wave Films",
                            Synopsis = "Two teenagers mysteriously swap bodies and try to find each other.",
                            Title = "Your Name",
                            Year = 2016
                        },
                        new
                        {
                            Id = 34,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",
                            Episodes = 1,
                            Genre = "Drama,Fantasy,Romance",
                            MalScore = 8.5,
                            Studio = "CoMix Wave Films",
                            Synopsis = "A runaway boy meets a girl with the power to stop rain in Tokyo.",
                            Title = "Weathering with You",
                            Year = 2019
                        },
                        new
                        {
                            Id = 35,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1500/103005l.jpg",
                            Episodes = 11,
                            Genre = "Drama,Music,Romance,Slice of Life",
                            MalScore = 8.4000000000000004,
                            Studio = "Lerche",
                            Synopsis = "A guitarist meets a boy with a broken guitar and a haunted past.",
                            Title = "Given",
                            Year = 2019
                        },
                        new
                        {
                            Id = 36,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1521/99674l.jpg",
                            Episodes = 47,
                            Genre = "Drama,Music,Romance,Slice of Life",
                            MalScore = 8.5,
                            Studio = "Madhouse",
                            Synopsis = "Two girls named Nana meet on a train and become roommates in Tokyo.",
                            Title = "Nana",
                            Year = 2006
                        },
                        new
                        {
                            Id = 37,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1887/117644l.jpg",
                            Episodes = 26,
                            Genre = "Comedy,Drama,Romance,School",
                            MalScore = 8.1999999999999993,
                            Studio = "Bones",
                            Synopsis = "A scholarship student accidentally breaks a vase and must join a host club to repay the debt.",
                            Title = "Ouran High School Host Club",
                            Year = 2006
                        },
                        new
                        {
                            Id = 38,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1441/99991l.jpg",
                            Episodes = 25,
                            Genre = "Comedy,Drama,Romance,Slice of Life,Supernatural",
                            MalScore = 8.5,
                            Studio = "TMS Entertainment",
                            Synopsis = "A girl discovers a family secret — its members transform into Chinese zodiac animals.",
                            Title = "Fruits Basket",
                            Year = 2019
                        },
                        new
                        {
                            Id = 39,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1988/119581l.jpg",
                            Episodes = 25,
                            Genre = "Comedy,Sports",
                            MalScore = 8.0999999999999996,
                            Studio = "Production I.G",
                            Synopsis = "A phantom player joins a high school basketball team to take on the legendary Generation of Miracles.",
                            Title = "Kuroko's Basketball",
                            Year = 2012
                        },
                        new
                        {
                            Id = 40,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1337/99013l.jpg",
                            Episodes = 12,
                            Genre = "Comedy,Sports,Slice of Life",
                            MalScore = 7.7000000000000002,
                            Studio = "Kyoto Animation",
                            Synopsis = "A group of childhood friends reunite to form a competitive swim club.",
                            Title = "Free!",
                            Year = 2013
                        },
                        new
                        {
                            Id = 41,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/3/40451l.jpg",
                            Episodes = 25,
                            Genre = "Action,Adventure,Drama,Historical,Horror,Supernatural",
                            MalScore = 8.5999999999999996,
                            Studio = "OLM",
                            Synopsis = "A lone mercenary joins a band of warriors and faces supernatural evil.",
                            Title = "Berserk",
                            Year = 1997
                        },
                        new
                        {
                            Id = 42,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/6/73245l.jpg",
                            Episodes = 26,
                            Genre = "Action,Adventure,Comedy,Sci-Fi",
                            MalScore = 8.1999999999999993,
                            Studio = "Madhouse",
                            Synopsis = "A legendary gunman with a huge bounty wanders a desert planet spreading peace.",
                            Title = "Trigun",
                            Year = 1998
                        },
                        new
                        {
                            Id = 43,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
                            Episodes = 51,
                            Genre = "Action,Adventure,Drama,Fantasy",
                            MalScore = 8.0,
                            Studio = "Bones",
                            Synopsis = "Two brothers use alchemy to try to restore their bodies after a failed ritual.",
                            Title = "Fullmetal Alchemist (2003)",
                            Year = 2003
                        },
                        new
                        {
                            Id = 44,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",
                            Episodes = 27,
                            Genre = "Action,Adventure,Comedy,Mecha,Sci-Fi",
                            MalScore = 8.6999999999999993,
                            Studio = "Gainax",
                            Synopsis = "A boy from an underground village leads humanity to fight against oppressive overlords.",
                            Title = "Gurren Lagann",
                            Year = 2007
                        },
                        new
                        {
                            Id = 45,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1500/103005l.jpg",
                            Episodes = 12,
                            Genre = "Action,Adventure,Comedy,Supernatural",
                            MalScore = 7.9000000000000004,
                            Studio = "Bones",
                            Synopsis = "A minor god tries to build his own shrine and gets entangled with a girl's soul.",
                            Title = "Noragami",
                            Year = 2014
                        },
                        new
                        {
                            Id = 46,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1521/99674l.jpg",
                            Episodes = 24,
                            Genre = "Action,Adventure,Drama,Fantasy",
                            MalScore = 7.5,
                            Studio = "White Fox",
                            Synopsis = "A naive country boy joins an assassin group fighting against a corrupt empire.",
                            Title = "Akame ga Kill!",
                            Year = 2014
                        },
                        new
                        {
                            Id = 47,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1988/119581l.jpg",
                            Episodes = 22,
                            Genre = "Action,Comedy,School,Sci-Fi",
                            MalScore = 8.0999999999999996,
                            Studio = "Lerche",
                            Synopsis = "Students must assassinate their teacher who threatens to destroy the Earth.",
                            Title = "Assassination Classroom",
                            Year = 2015
                        },
                        new
                        {
                            Id = 48,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1337/99013l.jpg",
                            Episodes = 25,
                            Genre = "Action,Adventure,Drama,Fantasy",
                            MalScore = 8.0999999999999996,
                            Studio = "Kinema Citrus",
                            Synopsis = "A falsely accused hero must prove himself while protecting his world.",
                            Title = "The Rising of the Shield Hero",
                            Year = 2019
                        },
                        new
                        {
                            Id = 49,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/1441/99991l.jpg",
                            Episodes = 23,
                            Genre = "Action,Adventure,Fantasy,Romance",
                            MalScore = 7.7000000000000002,
                            Studio = "A-1 Pictures",
                            Synopsis = "The Underworld faces a massive invasion while Kirito remains unconscious.",
                            Title = "Sword Art Online: Alicization – War of Underworld",
                            Year = 2019
                        },
                        new
                        {
                            Id = 50,
                            CoverImageUrl = "https://cdn.myanimelist.net/images/anime/6/86733l.jpg",
                            Episodes = 24,
                            Genre = "Action,Comedy,Fantasy,Historical,Mystery,Supernatural",
                            MalScore = 7.7000000000000002,
                            Studio = "A-1 Pictures",
                            Synopsis = "A young nobleman makes a contract with a demon butler to avenge his family.",
                            Title = "Black Butler",
                            Year = 2008
                        });
                });

            modelBuilder.Entity("OtakuDex.Models.AnimeGenre", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("AnimeId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AnimeGenres");
                });

            modelBuilder.Entity("OtakuDex.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("OtakuDex.Models.CollectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("CollectionId");

                    b.ToTable("CollectionItems");
                });

            modelBuilder.Entity("OtakuDex.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("OtakuDex.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("OtakuDex.Models.AnimeGenre", b =>
                {
                    b.HasOne("OtakuDex.Models.Anime", "Anime")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtakuDex.Models.Genre", "Genre")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("OtakuDex.Models.CollectionItem", b =>
                {
                    b.HasOne("OtakuDex.Models.Anime", "Anime")
                        .WithMany("CollectionItems")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OtakuDex.Models.Collection", "Collection")
                        .WithMany("CollectionItems")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("OtakuDex.Models.Review", b =>
                {
                    b.HasOne("OtakuDex.Models.Anime", "Anime")
                        .WithMany("Reviews")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("OtakuDex.Models.Anime", b =>
                {
                    b.Navigation("AnimeGenres");

                    b.Navigation("CollectionItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("OtakuDex.Models.Collection", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("OtakuDex.Models.Genre", b =>
                {
                    b.Navigation("AnimeGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
